[2023-04-26T19:01:08.692+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-04-26T19:00:54.055609+00:00 [queued]>
[2023-04-26T19:01:08.772+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-04-26T19:00:54.055609+00:00 [queued]>
[2023-04-26T19:01:08.774+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T19:01:08.775+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-04-26T19:01:08.777+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T19:01:08.859+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-26 19:00:54.055609+00:00
[2023-04-26T19:01:08.894+0000] {standard_task_runner.py:55} INFO - Started process 98254 to run task
[2023-04-26T19:01:08.915+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2023-04-26T19:00:54.055609+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp9lsdnoqx']
[2023-04-26T19:01:08.921+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask create_table
[2023-04-26T19:01:09.153+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2023-04-26T19:00:54.055609+00:00 [running]> on host b1a900116e57
[2023-04-26T19:01:09.450+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T19:00:54.055609+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T19:00:54.055609+00:00
[2023-04-26T19:01:09.486+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-04-26T19:01:09.497+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2023-04-26T19:01:09.505+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2023-04-26T19:01:09.533+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230426T190054, start_date=20230426T190108, end_date=20230426T190109
[2023-04-26T19:01:09.649+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-04-26T19:01:09.772+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
