[2023-04-26T20:06:31.107+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-04-26T20:06:24.958615+00:00 [queued]>
[2023-04-26T20:06:31.126+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-04-26T20:06:24.958615+00:00 [queued]>
[2023-04-26T20:06:31.127+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T20:06:31.129+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-04-26T20:06:31.130+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T20:06:31.152+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-04-26 20:06:24.958615+00:00
[2023-04-26T20:06:31.165+0000] {standard_task_runner.py:55} INFO - Started process 1929 to run task
[2023-04-26T20:06:31.171+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-04-26T20:06:24.958615+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpm7i2rrtm']
[2023-04-26T20:06:31.174+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask is_api_available
[2023-04-26T20:06:31.258+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-04-26T20:06:24.958615+00:00 [running]> on host b1a900116e57
[2023-04-26T20:06:31.344+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T20:06:24.958615+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T20:06:24.958615+00:00
[2023-04-26T20:06:31.347+0000] {http.py:120} INFO - Poking: api/
[2023-04-26T20:06:31.370+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-04-26T20:06:31.451+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-04-26T20:06:32.316+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-04-26T20:06:32.368+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230426T200624, start_date=20230426T200631, end_date=20230426T200632
[2023-04-26T20:06:32.402+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-04-26T20:06:32.455+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
